### ISSUE TITLE
Correction de l'ordre d'importation des films notés de Allociné vers Letterboxd en respectant les filtres 'when added/rated (tri)

### ISSUE THREAD

**Issue by GeoffroyDutot** [Poudlardo/Allocine2Letterboxd#2]
Actuellement, le projet génère un fichier CSV des films notés sur Allociné, triés du plus récent au plus ancien. Cependant, lors de l'importation sur Letterboxd, les films les plus anciennement notés remontent en premier dans la liste, ce qui est contraire à l'attente des utilisateurs.

Proposition de solution : Maintenir le fonctionnement actuel du script qui enregistre les films du plus récent au plus vieux. Cependant, avant de créer le fichier CSV, inverser l'ordre des données pour placer les modifications les plus anciennes en premier. Cela garantira que lors de l'importation sur Letterboxd, les films les plus récemment notés apparaîtront en premier dans la liste avec les filtres filtres 'when added/rated', conformément aux attentes des utilisateurs.

**Comment by Poudlardo** [comment]
Bonne idée ! Je m'en suis occupé. Après test, ça semble fonctionné : quand tu importes sur Letterboxd, les films les plus récents apparaissent à présent.

**Comment by Poudlardo** [comment]
Bonne idée ! Je m'en suis occupé. Après test, ça semble fonctionner : quand tu importes sur Letterboxd, les films les plus récents apparaissent à présent.
